<?php

namespace AppBundle\Repository;

/**
 * AffectedProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectedProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
