fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_security_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /login

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

coresphere_console:
    resource: .
    type: extra
