user_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

login_barcode:
    path:    /login_barcode
    defaults: { _controller: UserBundle:Security:loginBarcode }
    
login_keyboard:
    path:   /login_keyboard
    defaults: { _controller: UserBundle:Security:loginKeyBoard }