user_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

#login_barcode:
 #   path:    /login_barcode
  #  defaults: { _controller: UserBundle:Security:loginBarcode }

fos_user_security_login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }