mark_upload:
    path: /mark_upload
    defaults: { _controller: AppBundle:Default:markUpload }
    
generate_codbare:
    path: /student_barcode
    defaults: { _controller: AppBundle:Default:studentBarcode }
    
mark_input:
    path: /mark_input/{section_id}/{evaluation_id}
    defaults: { _controller: AppBundle:Default:markInput }
    
mark_table:
    path: /mark_table/{section_id}
    defaults: { _controller: AppBundle:Default:markTable }
    
mark_table_std:
    path: /mark_table_std/{section_id}
    defaults: { _controller: AppBundle:Default:markTableStd }
    
shortyImportCSV:
    path: /admin/csv/import
    defaults:  { _controller: AppBundle:Default:importFile }
    
tacher_card:
    path: /teacher_card
    defaults:  { _controller: AppBundle:Default:teacherCard }