services:
    AppBundle\EventListener\RequestListener:
        arguments: ["@doctrine.orm.entity_manager", "@translator"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.admin.student:
        class: AppBundle\Admin\StudentAdmin
        arguments: [~, AppBundle\Entity\Student, AppBundle:StudentAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Student Information, label: Student }
        public: true

    app.admin.evaluation:
        class: AppBundle\Admin\EvaluationAdmin
        arguments: [~, AppBundle\Entity\Evaluation, AppBundle:EvaluationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Evaluation Task, label: Evaluation }
        public: true
        
    app.admin.mark:
        class: AppBundle\Admin\MarkAdmin
        arguments: [~, AppBundle\Entity\Mark, AppBundle:MarkAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Evaluation Task, label: Mark }
        public: true

    app.admin.evaluation_type:
        class: AppBundle\Admin\EvaluationTypeAdmin
        arguments: [~, AppBundle\Entity\EvaluationType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Evaluation Task, label: EvaluationType }
        public: true

    app.admin.section:
        class: AppBundle\Admin\SectionAdmin
        arguments: [~, AppBundle\Entity\Section, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Section }
        public: true

    app.admin.setting:
        class: AppBundle\Admin\SettingAdmin
        arguments: [~, AppBundle\Entity\Setting, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Setting Information, label: Setting }
        public: true
            
    console_command.csv_import:
        class: AppBundle\Command\CsvImportCommand
        arguments:
            -  "@doctrine.orm.entity_manager"
        tags: 
            - { name: console.command }
            
    app.utils:
        class: AppBundle\Service\Utils
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        
    app.utilsLTB:
        class: AppBundle\Service\UtilsLTB
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        
    app.utilsSTD:
        class: AppBundle\Service\UtilsSTD
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        
    app.build_marktable_handler:
        class: AppBundle\Service\BuildMarkTableHandler
        arguments: ["@doctrine.orm.entity_manager", "@app.utilsSTD"]
        
    app.build_marktableLTB_handler:
        class: AppBundle\Service\BuildMarkTableLTBHandler
        arguments: ["@doctrine.orm.entity_manager", "@app.utils"]
    
    app.admin.student_parent:
        class: AppBundle\Admin\StudentParentAdmin
        arguments: [~, AppBundle\Entity\StudentParent, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Student Information, label: StudentParent }
        public: true

    app.admin.main_teacher:
        class: AppBundle\Admin\MainTeacherAdmin
        arguments: [~, AppBundle\Entity\MainTeacher, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MainTeacher }
        public: true

    app.admin.teacher:
        class: AppBundle\Admin\TeacherAdmin
        arguments: [~, AppBundle\Entity\Teacher, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Teacher }
        public: true

    app.admin.sequence:
        class: AppBundle\Admin\SequenceAdmin
        arguments: [~, AppBundle\Entity\Sequence, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Teaching System, label: Sequence }
        public: true

    app.admin.level:
        class: AppBundle\Admin\LevelAdmin
        arguments: [~, AppBundle\Entity\Level, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Teaching System, label: Level }
        public: true

    app.admin.coefficient:
        class: AppBundle\Admin\CoefficientAdmin
        arguments: [~, AppBundle\Entity\Coefficient, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Teaching System, label: Coefficient }
        public: true

    app.admin.program:
        class: AppBundle\Admin\ProgramAdmin
        arguments: [~, AppBundle\Entity\Program, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Teaching System, label: Program, pager_type: simple }
        public: true

    app.admin.field:
        class: AppBundle\Admin\FieldAdmin
        arguments: [~, AppBundle\Entity\Field, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Teaching system, label: Field }
        public: true

    #app.admin.absence_compter:
     #   class: AppBundle\Admin\AbsenceCompterAdmin
      #  arguments: [~, AppBundle\Entity\AbsenceCompter, SonataAdminBundle:CRUD]
       # tags:
        #    - { name: sonata.admin, manager_type: orm, group: admin, label: AbsenceCompter }
        #public: true

    app.admin.cycle:
        class: AppBundle\Admin\CycleAdmin
        arguments: [~, AppBundle\Entity\Cycle, AppBundle:CycleAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cycle }
        public: true
